language: python
cache: pip
dist: xenial
python:
    - '3.6'
    - '3.7'
    - '3.8'
    - '3.9'
    - pypy3

env:
    - TOXENV=py

jobs:
    include:
        - python: '3.6'
          env: TOXENV=typing

install:
    - pip install -U codecov tox virtualenv
script:
    - tox
after_success:
    - codecov
